export const ApiRouters = {
  UNIT_NOT_LOGIN: "/Unit/Search",
  UNIT_LOGIN: "/Unit/Search/Auth",
  UNIT_LESSON_NOT_LOGIN: "/Lesson/Search",
  GET_DATA_LEARN: "/GetDataLearn",
  DASHBROADS_CHART: "/Dashbroads/Chart",
  DASHBROADS_CHART_LEVEL: "/Dashbroads/Statistical",
  QUESTION_SEARCH: "/FAQs/Search",
  STUDIED: "/Studied",
  NOTEBOOK: "/Notebook/Update",
  NOTEBOOK_SEARCH: "/Notebook/Search",
  DATA_REVIEW: "/DataReview",
  REVIEW: "/Review",
  SEARCH: "/Search",
  SEND_EMAIL_NOTIFY: "/SendEmailNotify",
  SEND_UPGRADE_ACCOUNT: "/AccountRequest/Create",
  VOCABULARY: "/VocabularyNotebook/",
  GETSTATICPAGESFO: "/GetStaticPagesFO",
  GROUPBYTYPEASYNCFO: "/GroupByTypeAsyncFO",
  SEARCHHASHTAGASYNC: "/SearchHashtagAsync",
  RULEREVIEW: "/RuleReview",
  SCHEDULEQUEUE: "/ScheduleQueue",
  UPDATEFIREBASETOKEN: "/UpdateFirebaseToken",
  GETSTATICPAGESDATAIL: "/GetStaticPagesDetail",
  UPDATEMPTIFIASYNC: "/UpdateNotifyAsync",
  SIGNOUT: "/SignOut",
};

export const BaseRouter = {
  COURSES: "/Courses",
  COURSES_UNIT: "/Courses/Unit",
  LEARN_AND_REVIEWS: "/LearnAndReviews",
  LEARN: "/Learners",
  BLOG: "/Blogs",
  DASHBROADS: "/Dashbroads",
  LANDINGPAGE: "/LandingPage",
  VOCABULARY: "/Vocabularys",
  STATICPAGESFOS: "/StaticPageFOs",
  NOTIQUEUES: "/NotiQueues",
  AUTH: "/Auth",
  NOTIFYS: "/Notifys",
};
