export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const LOGIN_MANUAL_REQUEST = "LOGIN_MANUAL_REQUEST";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SOCIAL_REQUEST = "LOGIN_SOCIAL_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";
